language: python

python:
  - "3.8"

services: mysql

env:
    - DJANGO=3.2.7 DB=sqlite3

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - cd mysite

#command to run the test suite
script:
  - python manage.py test