# Generated by Django 3.2.7 on 2021-09-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('salary', models.FloatField(default=0)),
                ('related_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_app.department')),
            ],
        ),
    ]
